### ISSUE TITLE
How do I override styling?

### ISSUE THREAD

**Issue by ghost** [mavidser/hugo-rocinante#1]
I have created an assets/css/<name of scss> folder here (with the same name and different). I have also changed this in the code

```
{{ range .Site.Params.customCSS -}}
    {{ $style := resources.Get . | resources.ToCSS $options }}
    <!-- {{ $style := resources.Get "css/custom.scss" | resources.ToCSS $options  }} -->
    <link rel="stylesheet" href="{{ $style.RelPermalink }}" />
{{- end }}
```

I have had no luck.

**Comment by mavidser** [comment]
I added the same code to my HTML and it worked fine for me. Can you share more details or the hugo project?

This is how I added customCSS to my `config.toml`:
```
[params]
  customCSS = ["/css/custom.scss"]
```

and the style lives in `assets/css/custom.scss`. Note that it needs to be a SCSS file if it's in the assets folder. Normal CSS files would be placed in the static folder, without the `resources.ToCSS` filter in the HTML

**Comment by ghost** [comment]
I left off the `/` at the front of the `customCSS` url, I'll try it with it later tonight. By the way, I am new to git submodules. If you updated your submodule, and I only wanted certain commits, i.e. not all changes? How does that work? 

I'm wondering if it's a better idea to clone your submodule and maintain a separate private copy as I plan to deviate significantly from the original design.

**Comment by mavidser** [comment]
Submodules point to a specific commit. So, even if I update my repo, your repo should remain unaffected as it would be checking out the commit specified by your repo.

You can fork this repo to maintain your own changes too, but you should do that only if you want to make that theme easily available for others to use. 

If only for personal use, you can skip submodules and just put the content of this repo in `themes/rocinante` folder as then you won't have to update two repositories to update your website's theme (first the theme repo, then updating the website's submodule to the latest commit)

**Comment by ghost** [comment]
I went with the last option you mentioned. None of the other ones worked. Thank you!
