### ISSUE TITLE
Banner on 'post' type

### ISSUE THREAD

**Issue by adriennefranke** [mavidser/hugo-rocinante#4]
Hi! Is it possible to have a banner image on just a 'post' type rather than only on the 'photos' type? Or instead, ensure an image I have at the beginning of a 'post' be a part of the preview on the homepage? Thanks!

**Comment by philippheumann** [comment]
Hi Adrienne! If you want an image to also appear on the post preview, you can link it within the markdown file above `<!--more-->`. The image now appears in the preview as well as in the post itself. Attached I have two pictures how your result could look like - in the post as well as in the preview. I hope this helps!
Here is a small example: 

```
---
title:  This is a blog post
date: 2017-10-10
tags: ["Something", "Samples", "Example"]
---

Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. 

![This is a test picture.](/images/test_picture.jpg)

<!--more-->

# Heading 1
Lorem ipsum dolor [link](/), consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. 
```
![Image_Post](https://user-images.githubusercontent.com/47601255/105628709-cf125300-5e3e-11eb-8798-ce2e33188cfd.png)
![Image_Preview](https://user-images.githubusercontent.com/47601255/105628712-d174ad00-5e3e-11eb-88e7-12730a5bff1a.png)

**Comment by adriennefranke** [comment]
@philippheumann Amazing, thank you so much!!
